nodeLinker: node-modules

npmRegistryServer: "https://trial8or2vi.jfrog.io/artifactory/api/npm/dav-npm/"

npmRegistries:
  "https://trial8or2vi.jfrog.io/artifactory/api/npm/dav-npm/":
    npmAuthToken: "${JFROG_ACCESS_TOKEN}"
    npmAlwaysAuth: true

